services:
  postgres:
    container_name: postgres_pet_project
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - ../../postgres-data-14:/var/lib/postgresql/data
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

volumes:
  postgres-data: